### ISSUE TITLE
Ubuntu 16.04 Error in child process. 

### ISSUE THREAD

**Issue by shopglobal** [brandonlehmann/turtlecoind-ha#1]
Let me start out by saying, I like the sound of this very much. I am trying to get it to work. So far this is the output:
```
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has started...  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind is attempting to synchronize with the network...
Fri, 23 Mar 2018 05:36:13 GMT: Error in child process...: Error: read EIO
Fri, 23 Mar 2018 05:36:13 GMT: TurtleCoind has closed... restarting process...
```

I am dropping this in the the same directory as TurtleCoin and I have made the path absolute with dirname + './TurtleCoind'; 

Should work, but it's repetitive and not loading the daemon at all..
Any help would be appreciated. Thanks so much. Looking forward to contributing as I am a full stack developer with node experience just new to this project. Thanks!

**Comment by brandonlehmann** [comment]
Hi,

Thanks for the feedback. It looks like the TurtleCoind binary is  exiting immediately after it attempts to start (I'll have to make that more clear in the logging). 

I have a couple of questions regarding your setup that will help me understand where the error might be.

- What version of TurtleCoind are you running?
- Have you verified that TurtleCoind starts with the same arguments as you provided via the wrapper? (ex. ./TurtleCoind --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091

Thanks for giving it a try and I'm sure we'll get this sorted.

**Comment by shopglobal** [comment]
Hello and thank you for your help, I'm running the latest release from the
GitHub

Ubuntu 16.04
```
https://github.com/turtlecoin/turtlecoin/releases/download/v0.3.2/turtlecoin-v0.3.2-linux.zip
```

So far my daemon is loading fine outside of the wrapper. So I can launch
the Damon ./TurtleCoind but would like to make use of the API.

**Comment by brandonlehmann** [comment]
I'll add a bit more logging today to find out what's going on.

**Comment by brandonlehmann** [comment]
I've pushed in a bit of additional logging. Please update from the master branch and give it another go.

**Comment by shopglobal** [comment]
Hey Brandon
After pulling master I ran ```npm install && node service.js```
Tested on 0.10.48 and latest stable 9

```
root@volleyd:~/trtl/turtlecoind-ha# node service.js
/root/trtl/turtlecoind-ha/turtlecoind-ha.js:49
    this.error('error', util.format('%s could not be found'))
         ^

TypeError: this.error is not a function
    at TurtleCoind.start (/root/trtl/turtlecoind-ha/turtlecoind-ha.js:49:10)
    at Object.<anonymous> (/root/trtl/turtlecoind-ha/service.js:48:8)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```
So I replaced a few lines with console.log, and added path with __dirname to the TurtleCoind 
```
var path = require("path");
let dirs = __dirname + '/TurtleCoind';
```
I will make a pull request, but it's still not quite getting me there. 
```
Here's what I am getting now

```
Sat, 24 Mar 2018 00:11:19 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 00:11:19 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 00:11:23 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
Sat, 24 Mar 2018 00:11:23 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 00:11:23 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 00:11:23 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 00:11:27 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
Sat, 24 Mar 2018 00:11:27 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 00:11:27 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 00:11:27 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 00:11:31 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
Sat, 24 Mar 2018 00:11:31 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 00:11:31 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 00:11:31 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 00:11:35 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
Sat, 24 Mar 2018 00:11:35 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 00:11:35 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 00:11:35 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 00:11:40 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
Sat, 24 Mar 2018 00:11:40 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 00:11:40 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 00:11:40 GMT: Error in child process...: Error: read EIO

```

So I am seeing less restarts, as you can see with the timestamps. Every 4-5 seconds rather than how I was getting a blasted with repeat restart logs earlier.

**Comment by brandonlehmann** [comment]
I do see where I pushed up an incomplete commit that broke that logging. I'm resolving that now.

If I'm reading your PR correctly, did you leave the service.js params pointed at "/path/to/TurtleCoind" ?

**Comment by brandonlehmann** [comment]
Resolved logging error in https://github.com/brandonlehmann/turtlecoind-ha/commit/ced1d834fa527a66cc6e254fced7e78e2db3e6be

**Comment by shopglobal** [comment]
I only share master friendly code in my pulls. 
You can see in the logs above
```/home/trtls/trtls/turtlecoind-ha/TurtleCoind```
This is shown because In

In my branch I have the following:

```
let dirs = __dirname + '/TurtleCoind';

var daemon = new TurtleCoind({
  path: __dirname + '/TurtleCoind' 
})
``

**Comment by shopglobal** [comment]
```
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has closed... restarting process...
/home/trtls/trtls/turtlecoind-ha/TurtleCoind
/home/trtls/trtls/turtlecoind-ha/.TurtleCoin
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind has started... /home/trtls/trtls/turtlecoind-ha/TurtleCoind  --data-dir /home/trtls/trtls/turtlecoind-ha/.TurtleCoin --rpc-bind-ip 127.0.0.1 --rpc-bind-port 24091
Sat, 24 Mar 2018 01:30:22 GMT: TurtleCoind is attempting to synchronize with the network...
Sat, 24 Mar 2018 01:30:22 GMT: Error in child process...: Error: read EIO

```

**Comment by brandonlehmann** [comment]
It appears that the child process is closing on it's own after starting. You don't have another process running on that same port (either the p2p port or the rpc port), do you?

**Comment by brandonlehmann** [comment]
I think I've figured out your use case and have incorporated some of your PR ideas into 302fca78b8b08ecc83decafaa856b05e808c8ac6

**Comment by shopglobal** [comment]
I'm going to test this latest commit out, it looks promising.

**Comment by brandonlehmann** [comment]
Work any better for you?

**Comment by shopglobal** [comment]
Reserved.
Will have time this evening, have been traveling.

**Comment by shopglobal** [comment]
Now this is clean code!
